# Generated by Django 4.2.8 on 2023-12-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('Novice', 'Novice'), ('Competent', 'Competent'), ('Expert', 'Expert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_scheduling_app.nurse')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_scheduling_app.shift')),
            ],
        ),
    ]
